spring:
  application:
    name: getWay
  cloud:
    gateway:
      routes:
        - id: info
          #uri: http://127.0.0.1:8084
          uri: lb://consumption
          predicates:
#            - Path=/consumption/** #请求URL匹配模式
             - Path=/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 10010
