server:
  port: 10220
spring:
  application:
    name: activiti
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zhou
    password: qq1719351997
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&amp&useUnicode=true&amp&characterEncoding=utf8&serverTimezone=UTC&nullCatalogMeansCurrent=true
  activiti:
    check-process-definitions: false
    db-identity-used: false
    async-executor-activate: false
    # 自动生成Activiti相关表 第一次生成后建议关闭提高运行速度
    database-schema-update: true
    # 保存历史数据级别设置为full最高级别，便于历史数据的追溯,建议使用
    history-level: full
    process-definition-location-prefix: classpath:/processes/



