server:
  port: 8087
#eureka:
#  instance:
#    hostname: ribbon
#  client:
#    service-url:
#      defaultZone: http://localhost:8083/eureka/
spring:
  application:
    name: ribbon
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
