server:
  port: 10220
spring:
  application:
    name: activiti
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zhou
    password: qq1719351997
    url: jdbc:mysql://localhost:3306/activiti?useSSL=false&amp&useUnicode=true&amp&characterEncoding=utf8&serverTimezone=UTC&nullCatalogMeansCurrent=true


