dubbo:
  application:
    name: dubbo-springboot-demo-Consumer
  protocol:
    name: dubbo
    port: 20885
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
server:
  port: 8001
