dubbo:
  application:
    name: dubbo-springboot-demo-Provider
  protocol:
    name: dubbo
    port: 20884
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
server:
  port: 8002
