name: Sync from Gitee

on:
  repository_dispatch:
    types: [gitee_sync]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull from Gitee
        run: |
          git remote add gitee https://gitee.com/superstudy1/study-datum.git
          git pull gitee master --tags
        env:
          GITEE_TOKEN: ${{ secrets.ACTIONTOKEN }}

      - name: Push to GitHub
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONTOKEN }}
