name: Sync from Gitee

on:
  push:
    branches:
      - master  # 可以根据需要修改为你的默认分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull from Gitee
        run: |
          git remote add gitee https://gitee.com/superstudy1/study-datum.git
          git pull gitee master --tags
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}

      - name: Push to GitHub
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
