name: Sync from Gitee

on:
   push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "startz"
          git config --global user.email "1719351997@qq.com"

      - name: Pull from Gitee
        id: pull
        run: |
          git remote add gitee https://gitee.com/superstudy1/study-datum.git
          git fetch gitee
          git merge -Xtheirs gitee/master
        env:
          GITEE_TOKEN: ${{ secrets.ACTIONTOKEN }}
        continue-on-error: true

      - name: Push to GitHub
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONTOKEN }}
